// Package dashboard_stats provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package dashboard_stats

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for GrossMeasureDashboardType.
const (
	GrossMeasureDashboardTypeOTHER GrossMeasureDashboardType = "OTHER"

	GrossMeasureDashboardTypeTLG GrossMeasureDashboardType = "TLG"

	GrossMeasureDashboardTypeTLM GrossMeasureDashboardType = "TLM"
)

// Defines values for GrossMeasureDashboardCUPSType.
const (
	GrossMeasureDashboardCUPSTypeOTHER GrossMeasureDashboardCUPSType = "OTHER"

	GrossMeasureDashboardCUPSTypeTLG GrossMeasureDashboardCUPSType = "TLG"

	GrossMeasureDashboardCUPSTypeTLM GrossMeasureDashboardCUPSType = "TLM"
)

// GrossMeasureDashboard defines model for GrossMeasureDashboard.
type GrossMeasureDashboard struct {
	DistributorId           string                        `json:"distributor_id"`
	GrossMeasuresDailyStats *[]GrossMeasureDashboardDaily `json:"gross_measures_daily_stats,omitempty"`
	Month                   int                           `json:"month"`
	Type                    GrossMeasureDashboardType     `json:"type"`
	Year                    int                           `json:"year"`
}

// GrossMeasureDashboardType defines model for GrossMeasureDashboard.Type.
type GrossMeasureDashboardType string

// GrossMeasureDashboardCUPS defines model for GrossMeasureDashboardCUPS.
type GrossMeasureDashboardCUPS struct {
	Cups                    string                        `json:"cups"`
	DistributorId           string                        `json:"distributor_id"`
	GrossMeasuresDailyStats *[]GrossMeasureDashboardDaily `json:"gross_measures_daily_stats,omitempty"`
	Month                   int                           `json:"month"`
	SerialNumber            string                        `json:"serial_number"`
	ServicePointType        string                        `json:"service_point_type"`
	ServiceType             string                        `json:"service_type"`
	Type                    GrossMeasureDashboardCUPSType `json:"type"`
	Year                    int                           `json:"year"`
}

// GrossMeasureDashboardCUPSType defines model for GrossMeasureDashboardCUPS.Type.
type GrossMeasureDashboardCUPSType string

// GrossMeasureDashboardDaily defines model for GrossMeasureDashboardDaily.
type GrossMeasureDashboardDaily struct {
	DailyClosure           int  `json:"daily_closure"`
	Day                    *int `json:"day,omitempty"`
	ExpectedDailyClosure   int  `json:"expected_daily_closure"`
	ExpectedHourlyCurve    int  `json:"expected_hourly_curve"`
	ExpectedMonthlyClosure int  `json:"expected_monthly_closure"`
	ExpectedQuarterlyCurve int  `json:"expected_quarterly_curve"`
	HourlyCurve            int  `json:"hourly_curve"`
	MonthlyClosure         int  `json:"monthly_closure"`
	QuarterlyCurve         int  `json:"quarterly_curve"`
}

// GrossMeasureDashboardList defines model for GrossMeasureDashboardList.
type GrossMeasureDashboardList []GrossMeasureDashboard

// Pagination defines model for Pagination.
type Pagination struct {
	Links struct {
		// url for request next list
		Next *string `json:"next,omitempty"`

		// url for request previous list
		Prev *string `json:"prev,omitempty"`

		// url for request current list
		Self string `json:"self"`
	} `json:"_links"`
	Count  int  `json:"count"`
	Limit  int  `json:"limit"`
	Offset *int `json:"offset,omitempty"`
	Size   int  `json:"size"`
}

// GetGrossMeasureDashboardCUPSResponse defines model for GetGrossMeasureDashboardCUPSResponse.
type GetGrossMeasureDashboardCUPSResponse struct {
	// Embedded struct due to allOf(#/components/schemas/Pagination)
	Pagination `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Results []GrossMeasureDashboardCUPS `json:"results"`
}

// GetGrossMeasureDashboardResponse defines model for GetGrossMeasureDashboardResponse.
type GetGrossMeasureDashboardResponse GrossMeasureDashboardList

// GetProcessMeasureStatisticsByCupsParams defines parameters for GetProcessMeasureStatisticsByCups.
type GetProcessMeasureStatisticsByCupsParams struct {
	// distributor id
	DistributorId string `json:"distributor_id"`

	// Number of month
	Month int `json:"month"`

	// Number of year
	Year int `json:"year"`

	// Type of measurement config
	Type GetProcessMeasureStatisticsByCupsParamsType `json:"type"`

	// Flag for ghost equipments
	Ghost bool `json:"ghost"`

	// The number of items to skip before starting to collect the result set
	Offset *int `json:"offset,omitempty"`

	// The numbers of items to return
	Limit int `json:"limit"`
}

// GetProcessMeasureStatisticsByCupsParamsType defines parameters for GetProcessMeasureStatisticsByCups.
type GetProcessMeasureStatisticsByCupsParamsType string

// GetDashboardGrossMeasureParams defines parameters for GetDashboardGrossMeasure.
type GetDashboardGrossMeasureParams struct {
	// distributor id
	DistributorId string `json:"distributor_id"`

	// Number of month
	Month int `json:"month"`

	// Number of year
	Year int `json:"year"`

	// Type of measurement config
	Type GetDashboardGrossMeasureParamsType `json:"type"`
}

// GetDashboardGrossMeasureParamsType defines parameters for GetDashboardGrossMeasure.
type GetDashboardGrossMeasureParamsType string
