// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package http

import "github.com/gin-gonic/gin"

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authorization users from bearer token
	// (GET /me)
	AuthorizationUser(ctx *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []gin.HandlerFunc
}

// AuthorizationUser operation middleware
func (siw *ServerInterfaceWrapper) AuthorizationUser(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{""})

	siw.Handler.AuthorizationUser(c)
}

// RegisterHandlerAuthorizationUser creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlerAuthorizationUser(router *gin.RouterGroup, si ServerInterface) *gin.RouterGroup {
	return RegisterHandlerWithMiddlewaresAuthorizationUser(router, si, []gin.HandlerFunc{})
}

// RegisterHandlerWithMiddlewaresAuthorizationUser creates http.Handler with additional options
func RegisterHandlerWithMiddlewaresAuthorizationUser(router *gin.RouterGroup, si ServerInterface, middlewares []gin.HandlerFunc) *gin.RouterGroup {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: middlewares,
	}

	m := append(middlewares, wrapper.AuthorizationUser)

	router.GET("/me", m...)

	return router
}
