// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package http

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// User object
type User struct {
	Distributors []struct {
		Id   string `json:"id"`
		Name string `json:"name"`
		Role struct {
			Id   string `json:"id"`
			Name string `json:"name"`
		} `json:"role"`
	} `json:"distributors"`
	Email   string `json:"email"`
	Id      string `json:"id"`
	IsAdmin bool   `json:"is_admin"`
	Name    string `json:"name"`
}

// User object
type Me User
