steps:
  - id: Run Unit Tests
    name: golang:1.18-buster
    entrypoint: /bin/bash
    args:
    - -c
    - |
      go test -parallel 5 ./...

  - id: 'Build App'
    name: 'gcr.io/k8s-skaffold/skaffold:v1.38.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        skaffold config set --global collect-metrics false
        skaffold build --file-output build.json --push --default-repo eu.gcr.io/$PROJECT_ID --profile ${_PROFILE}

  - id: 'Deploy App'
    name: 'gcr.io/k8s-skaffold/skaffold:v1.38.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        skaffold config set --global collect-metrics false
        gcloud container clusters get-credentials "$$CLOUDSDK_CONTAINER_CLUSTER" --zone "$$CLOUDSDK_COMPUTE_ZONE" --project ${PROJECT_ID}
        skaffold deploy -a build.json --profile ${_PROFILE}
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

timeout: 900s
options:
  machineType: N1_HIGHCPU_8