// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	context "context"

	db "bitbucket.org/sercide/data-ingestion/pkg/db"
	mock "github.com/stretchr/testify/mock"

	process_billing "bitbucket.org/sercide/data-ingestion/internal/billing_measures"

	testing "testing"
)

// BillingSchedulerRepository is an autogenerated mock type for the BillingSchedulerRepository type
type BillingSchedulerRepository struct {
	mock.Mock
}

// DeleteScheduler provides a mock function with given fields: ctx, id
func (_m *BillingSchedulerRepository) DeleteScheduler(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetScheduler provides a mock function with given fields: ctx, id
func (_m *BillingSchedulerRepository) GetScheduler(ctx context.Context, id string) (process_billing.Scheduler, error) {
	ret := _m.Called(ctx, id)

	var r0 process_billing.Scheduler
	if rf, ok := ret.Get(0).(func(context.Context, string) process_billing.Scheduler); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(process_billing.Scheduler)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListScheduler provides a mock function with given fields: ctx, query
func (_m *BillingSchedulerRepository) ListScheduler(ctx context.Context, query db.Pagination) ([]process_billing.Scheduler, int, error) {
	ret := _m.Called(ctx, query)

	var r0 []process_billing.Scheduler
	if rf, ok := ret.Get(0).(func(context.Context, db.Pagination) []process_billing.Scheduler); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]process_billing.Scheduler)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, db.Pagination) int); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, db.Pagination) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SaveScheduler provides a mock function with given fields: ctx, s
func (_m *BillingSchedulerRepository) SaveScheduler(ctx context.Context, s process_billing.Scheduler) error {
	ret := _m.Called(ctx, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, process_billing.Scheduler) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchScheduler provides a mock function with given fields: ctx, search
func (_m *BillingSchedulerRepository) SearchScheduler(ctx context.Context, search process_billing.SearchScheduler) ([]process_billing.Scheduler, error) {
	ret := _m.Called(ctx, search)

	var r0 []process_billing.Scheduler
	if rf, ok := ret.Get(0).(func(context.Context, process_billing.SearchScheduler) []process_billing.Scheduler); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]process_billing.Scheduler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, process_billing.SearchScheduler) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBillingSchedulerRepository creates a new instance of BillingSchedulerRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewBillingSchedulerRepository(t testing.TB) *BillingSchedulerRepository {
	mock := &BillingSchedulerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
