// Package tariff provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package tariff

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for TariffsCoef.
const (
	TariffsCoefA TariffsCoef = "A"

	TariffsCoefB TariffsCoef = "B"

	TariffsCoefC TariffsCoef = "C"

	TariffsCoefD TariffsCoef = "D"
)

// Defines values for TariffsTensionLevel.
const (
	TariffsTensionLevelAT TariffsTensionLevel = "AT"

	TariffsTensionLevelBT TariffsTensionLevel = "BT"

	TariffsTensionLevelMT TariffsTensionLevel = "MT"
)

// Tariffs object
type TariffCalendar struct {
	CalendarCode   string `json:"calendar_code"`
	EndDate        string `json:"end_date"`
	GeographicCode string `json:"geographic_code"`
	StartDate      string `json:"start_date"`
	TariffCode     string `json:"tariff_code"`
}

// Tariffs object
type Tariffs struct {
	CalendarCode string              `json:"calendar_code"`
	CodeOdos     string              `json:"code_odos"`
	CodeOne      string              `json:"code_one"`
	Coef         TariffsCoef         `json:"coef"`
	Description  string              `json:"description"`
	GeographicId string              `json:"geographic_id"`
	Id           string              `json:"id"`
	Periods      int                 `json:"periods"`
	TariffCode   string              `json:"tariff_code"`
	TensionLevel TariffsTensionLevel `json:"tension_level"`
}

// TariffsCoef defines model for Tariffs.Coef.
type TariffsCoef string

// TariffsTensionLevel defines model for Tariffs.TensionLevel.
type TariffsTensionLevel string

// TariffCalendarResponseList defines model for TariffCalendarResponseList.
type TariffCalendarResponseList struct {
	Links struct {
		// url for request next list
		Next *string `json:"next,omitempty"`

		// url for request previous list
		Prev *string `json:"prev,omitempty"`

		// url for request current list
		Self string `json:"self"`
	} `json:"_links"`
	Count   int              `json:"count"`
	Limit   int              `json:"limit"`
	Offset  *int             `json:"offset,omitempty"`
	Results []TariffCalendar `json:"results"`
	Size    int              `json:"size"`
}

// TariffResponseList defines model for TariffResponseList.
type TariffResponseList struct {
	Links struct {
		// url for request next list
		Next *string `json:"next,omitempty"`

		// url for request previous list
		Prev *string `json:"prev,omitempty"`

		// url for request current list
		Self string `json:"self"`
	} `json:"_links"`
	Count   int       `json:"count"`
	Limit   int       `json:"limit"`
	Offset  *int      `json:"offset,omitempty"`
	Results []Tariffs `json:"results"`
	Size    int       `json:"size"`
}

// GetAllTariffsParams defines parameters for GetAllTariffs.
type GetAllTariffsParams struct {
	// The number of items to skip before starting to collect the result set
	Offset *int `json:"offset,omitempty"`

	// The numbers of items to return
	Limit int `json:"limit"`

	// Search text
	Q *string `json:"q,omitempty"`

	// short by
	Sort *[]string `json:"sort,omitempty"`
}

// GetTariffsCalendarParams defines parameters for GetTariffsCalendar.
type GetTariffsCalendarParams struct {
	// The number of items to skip before starting to collect the result set
	Offset *int `json:"offset,omitempty"`

	// The numbers of items to return
	Limit int `json:"limit"`

	// Search text
	Q *string `json:"q,omitempty"`

	// short by
	Sort *[]string `json:"sort,omitempty"`
}

// InsertTariffsJSONRequestBody defines body for InsertTariffs for application/json ContentType.
type InsertTariffsJSONRequestBody Tariffs

// ModifyTariffsJSONRequestBody defines body for ModifyTariffs for application/json ContentType.
type ModifyTariffsJSONRequestBody Tariffs
