// Package seasons provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package seasons

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// day_types object
type DayTypes struct {
	Id        string `json:"id"`
	IsFestive bool   `json:"isFestive"`
	Month     int    `json:"month"`
	Name      string `json:"name"`
	SeasonId  string `json:"season_id"`
}

// seasons object
type Seasons struct {
	Description    string `json:"description"`
	GeographicCode string `json:"geographic_code"`
	Id             string `json:"id"`
	Name           string `json:"name"`
}

// DayTypesResponseList defines model for DayTypesResponseList.
type DayTypesResponseList struct {
	Links struct {
		// url for request next list
		Next *string `json:"next,omitempty"`

		// url for request previous list
		Prev *string `json:"prev,omitempty"`

		// url for request current list
		Self string `json:"self"`
	} `json:"_links"`
	Count   int        `json:"count"`
	Limit   int        `json:"limit"`
	Offset  *int       `json:"offset,omitempty"`
	Results []DayTypes `json:"results"`
	Size    int        `json:"size"`
}

// SeasonsResponseList defines model for SeasonsResponseList.
type SeasonsResponseList struct {
	Links struct {
		// url for request next list
		Next *string `json:"next,omitempty"`

		// url for request previous list
		Prev *string `json:"prev,omitempty"`

		// url for request current list
		Self string `json:"self"`
	} `json:"_links"`
	Count   int       `json:"count"`
	Limit   int       `json:"limit"`
	Offset  *int      `json:"offset,omitempty"`
	Results []Seasons `json:"results"`
	Size    int       `json:"size"`
}

// GetAllSeasonsParams defines parameters for GetAllSeasons.
type GetAllSeasonsParams struct {
	// The number of items to skip before starting to collect the result set
	Offset *int `json:"offset,omitempty"`

	// The number of items to return
	Limit int `json:"limit"`

	// Search text
	Q *string `json:"q,omitempty"`

	// short by
	Sort *[]string `json:"sort,omitempty"`
}

// GetAllDayTypesParams defines parameters for GetAllDayTypes.
type GetAllDayTypesParams struct {
	// The number of items to skip before starting to collect the result set
	Offset *int `json:"offset,omitempty"`

	// The numbers of items to return
	Limit int `json:"limit"`

	// Search text
	Q *string `json:"q,omitempty"`

	// short by
	Sort *[]string `json:"sort,omitempty"`
}

// InsertSeasonJSONRequestBody defines body for InsertSeason for application/json ContentType.
type InsertSeasonJSONRequestBody Seasons

// ModifyDayTypeJSONRequestBody defines body for ModifyDayType for application/json ContentType.
type ModifyDayTypeJSONRequestBody DayTypes

// ModifySeasonJSONRequestBody defines body for ModifySeason for application/json ContentType.
type ModifySeasonJSONRequestBody Seasons

// InsertDayTypeJSONRequestBody defines body for InsertDayType for application/json ContentType.
type InsertDayTypeJSONRequestBody DayTypes
