// Package generate_calendars provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package generate_calendars

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)
