// Package festive_days provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package festive_days

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// festive days object
type FestiveDays struct {
	Date         string `json:"date"`
	Description  string `json:"description"`
	GeographicId string `json:"geographic_id"`
	Id           string `json:"id"`
}

// FestiveDaysList defines model for FestiveDaysList.
type FestiveDaysList struct {
	Links struct {
		// url for request next list
		Next *string `json:"next,omitempty"`

		// url for request previous list
		Prev *string `json:"prev,omitempty"`

		// url for request current list
		Self string `json:"self"`
	} `json:"_links"`
	Count   int           `json:"count"`
	Limit   int           `json:"limit"`
	Offset  *int          `json:"offset,omitempty"`
	Results []FestiveDays `json:"results"`
	Size    int           `json:"size"`
}

// festive days object
type GetFestiveDay FestiveDays

// festive days object
type FestiveDay FestiveDays

// ListFestiveDaysParams defines parameters for ListFestiveDays.
type ListFestiveDaysParams struct {
	// The number of items to skip before starting to collect the result set
	Offset *int `json:"offset,omitempty"`

	// The numbers of items to return
	Limit *int `json:"limit,omitempty"`

	// Search text
	Q *string `json:"q,omitempty"`

	// short by
	Sort *[]string `json:"sort,omitempty"`
}

// PostFestiveDayJSONRequestBody defines body for PostFestiveDay for application/json ContentType.
type PostFestiveDayJSONRequestBody FestiveDay

// PutFestiveDayJSONRequestBody defines body for PutFestiveDay for application/json ContentType.
type PutFestiveDayJSONRequestBody FestiveDay
