// Package geographic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package geographic

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// geographic zones object
type GeographicZoneWithId struct {
	Code        string `json:"code"`
	Description string `json:"description"`
	Id          string `json:"id"`
}

// geographic zones object
type GeographicZones struct {
	Code        string `json:"code"`
	Description string `json:"description"`
	Id          string `json:"id"`
}

// GeographicResponseList defines model for GeographicResponseList.
type GeographicResponseList struct {
	Links struct {
		// url for request next list
		Next *string `json:"next,omitempty"`

		// url for request previous list
		Prev *string `json:"prev,omitempty"`

		// url for request current list
		Self string `json:"self"`
	} `json:"_links"`
	Count   int                    `json:"count"`
	Limit   int                    `json:"limit"`
	Offset  *int                   `json:"offset,omitempty"`
	Results []GeographicZoneWithId `json:"results"`
	Size    int                    `json:"size"`
}

// GetAllGeographicZonesParams defines parameters for GetAllGeographicZones.
type GetAllGeographicZonesParams struct {
	// The number of items to skip before starting to collect the result set
	Offset *int `json:"offset,omitempty"`

	// The numbers of items to return
	Limit int `json:"limit"`

	// Search text
	Q *string `json:"q,omitempty"`

	// short by
	Sort *[]string `json:"sort,omitempty"`
}

// InsertGeographicZoneJSONRequestBody defines body for InsertGeographicZone for application/json ContentType.
type InsertGeographicZoneJSONRequestBody GeographicZones

// ModifyGeographicZoneJSONRequestBody defines body for ModifyGeographicZone for application/json ContentType.
type ModifyGeographicZoneJSONRequestBody GeographicZones
