openapi: 3.0.0
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost:8080
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
info:
  version: 1.0.0
  title: API Auth
tags:
  - name: auth
paths:
  /me:
    get:
      security:
        - BearerAuth: []
      tags:
        - auth
      summary: Authorization users from bearer token
      description: ''
      operationId: authorization user
      responses:
        '200':
          $ref: '#/components/responses/Me'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Me:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'

    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    User:
      type: object
      description: User object
      required:
        - id
        - name
        - email
        - is_admin
        - distributors
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        is_admin:
          type: boolean
        distributors:
          type: array
          items:
            type: object
            required:
              - id
              - name
              - role
            properties:
              id:
                type: string
              name:
                type: string
              role:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string
