openapi: 3.0.0
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost:8080
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
info:
  version: 1.0.0
  title: API Auth
paths:
  /admin/master-tables/generate/calendars:
    post:
      security:
        - BearerAuth: []
      tags:
        - Calendars
      summary: Generate all calendars
      description: 'Generate all calendars'
      operationId: generate calendars periods

      responses:
        '200':
          description: success operation
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /admin/master-tables/generate/festive_days:
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - Festive days
      summary: Generate Festive Days
      description: 'Generate Festive Days'
      operationId: generate festive days

      responses:
        '200':
          description: success operation
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

