// Package scheduler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package scheduler

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ProcessMeasureSchedulerUpdatableMeterType.
const (
	ProcessMeasureSchedulerUpdatableMeterTypeOTHER ProcessMeasureSchedulerUpdatableMeterType = "OTHER"

	ProcessMeasureSchedulerUpdatableMeterTypeTLG ProcessMeasureSchedulerUpdatableMeterType = "TLG"

	ProcessMeasureSchedulerUpdatableMeterTypeTLM ProcessMeasureSchedulerUpdatableMeterType = "TLM"
)

// Defines values for ProcessMeasureSchedulerUpdatablePointType.
const (
	ProcessMeasureSchedulerUpdatablePointTypeN1 ProcessMeasureSchedulerUpdatablePointType = "1"

	ProcessMeasureSchedulerUpdatablePointTypeN2 ProcessMeasureSchedulerUpdatablePointType = "2"

	ProcessMeasureSchedulerUpdatablePointTypeN3 ProcessMeasureSchedulerUpdatablePointType = "3"

	ProcessMeasureSchedulerUpdatablePointTypeN4 ProcessMeasureSchedulerUpdatablePointType = "4"

	ProcessMeasureSchedulerUpdatablePointTypeN5 ProcessMeasureSchedulerUpdatablePointType = "5"
)

// Defines values for ProcessMeasureSchedulerUpdatableReadingType.
const (
	ProcessMeasureSchedulerUpdatableReadingTypeBillingClosure ProcessMeasureSchedulerUpdatableReadingType = "billing_closure"

	ProcessMeasureSchedulerUpdatableReadingTypeCurve ProcessMeasureSchedulerUpdatableReadingType = "curve"

	ProcessMeasureSchedulerUpdatableReadingTypeDailyClosure ProcessMeasureSchedulerUpdatableReadingType = "daily_closure"
)

// Defines values for ProcessMeasureSchedulerUpdatableServiceType.
const (
	ProcessMeasureSchedulerUpdatableServiceTypeDC ProcessMeasureSchedulerUpdatableServiceType = "D-C"

	ProcessMeasureSchedulerUpdatableServiceTypeDD ProcessMeasureSchedulerUpdatableServiceType = "D-D"

	ProcessMeasureSchedulerUpdatableServiceTypeGD ProcessMeasureSchedulerUpdatableServiceType = "G-D"
)

// Pagination defines model for Pagination.
type Pagination struct {
	Links struct {
		// url for request next list
		Next *string `json:"next,omitempty"`

		// url for request previous list
		Prev *string `json:"prev,omitempty"`

		// url for request current list
		Self string `json:"self"`
	} `json:"_links"`
	Count  int  `json:"count"`
	Limit  int  `json:"limit"`
	Offset *int `json:"offset,omitempty"`
	Size   int  `json:"size"`
}

// ProcessMeasureScheduler defines model for ProcessMeasureScheduler.
type ProcessMeasureScheduler struct {
	// Embedded fields due to inline allOf schema
	Id string `json:"id"`
	// Embedded struct due to allOf(#/components/schemas/ProcessMeasureSchedulerBase)
	ProcessMeasureSchedulerBase `yaml:",inline"`
}

// ProcessMeasureSchedulerBase defines model for ProcessMeasureSchedulerBase.
type ProcessMeasureSchedulerBase struct {
	// Embedded fields due to inline allOf schema
	Name string `json:"name"`
	// Embedded struct due to allOf(#/components/schemas/ProcessMeasureSchedulerUpdatable)
	ProcessMeasureSchedulerUpdatable `yaml:",inline"`
}

// ProcessMeasureSchedulerUpdatable defines model for ProcessMeasureSchedulerUpdatable.
type ProcessMeasureSchedulerUpdatable struct {
	Description   string                                      `json:"description"`
	DistributorId *string                                     `json:"distributor_id,omitempty"`
	MeterType     []ProcessMeasureSchedulerUpdatableMeterType `binding:"dive,oneof='TLG' 'TLM' 'OTHER'" json:"meter_type"`
	PointType     ProcessMeasureSchedulerUpdatablePointType   `binding:"oneof='1' '2' '3' '4' '5'" json:"point_type"`
	ReadingType   ProcessMeasureSchedulerUpdatableReadingType `binding:"oneof='curve' 'daily_closure' 'billing_closure'" json:"reading_type"`
	Scheduler     string                                      `json:"scheduler"`
	ServiceType   ProcessMeasureSchedulerUpdatableServiceType `binding:"oneof='G-D' 'D-D' 'D-C'" json:"service_type"`
}

// ProcessMeasureSchedulerUpdatableMeterType defines model for ProcessMeasureSchedulerUpdatable.MeterType.
type ProcessMeasureSchedulerUpdatableMeterType string

// ProcessMeasureSchedulerUpdatablePointType defines model for ProcessMeasureSchedulerUpdatable.PointType.
type ProcessMeasureSchedulerUpdatablePointType string

// ProcessMeasureSchedulerUpdatableReadingType defines model for ProcessMeasureSchedulerUpdatable.ReadingType.
type ProcessMeasureSchedulerUpdatableReadingType string

// ProcessMeasureSchedulerUpdatableServiceType defines model for ProcessMeasureSchedulerUpdatable.ServiceType.
type ProcessMeasureSchedulerUpdatableServiceType string

// ListProcessMeasuresScheduler defines model for ListProcessMeasuresScheduler.
type ListProcessMeasuresScheduler struct {
	// Embedded struct due to allOf(#/components/schemas/Pagination)
	Pagination `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Results []ProcessMeasureScheduler `json:"results"`
}

// CreateProcessMeasureScheduler defines model for CreateProcessMeasureScheduler.
type CreateProcessMeasureScheduler ProcessMeasureSchedulerBase

// PatchProcessMeasureScheduler defines model for PatchProcessMeasureScheduler.
type PatchProcessMeasureScheduler ProcessMeasureSchedulerUpdatable

// ListProcessMeasuresSchedulerParams defines parameters for ListProcessMeasuresScheduler.
type ListProcessMeasuresSchedulerParams struct {
	// The number of items to skip before starting to collect the result set
	Offset *int `json:"offset,omitempty"`

	// The numbers of items to return
	Limit int `json:"limit"`
}

// CreateProcessMeasuresSchedulerJSONRequestBody defines body for CreateProcessMeasuresScheduler for application/json ContentType.
type CreateProcessMeasuresSchedulerJSONRequestBody CreateProcessMeasureScheduler

// PatchProcessMeasuresSchedulerJSONRequestBody defines body for PatchProcessMeasuresScheduler for application/json ContentType.
type PatchProcessMeasuresSchedulerJSONRequestBody PatchProcessMeasureScheduler
