apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-mongodb
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-ssd
  replication-type: none