// Package closures provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package closures

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ExecuteServicesType.
const (
	ExecuteServicesTypeCurve ExecuteServicesType = "curve"

	ExecuteServicesTypeDailyClose ExecuteServicesType = "daily-close"

	ExecuteServicesTypeMonthlyClose ExecuteServicesType = "monthly-close"
)

// Defines values for PeriodsMagnitud.
const (
	PeriodsMagnitudAE PeriodsMagnitud = "AE"

	PeriodsMagnitudAI PeriodsMagnitud = "AI"

	PeriodsMagnitudR1 PeriodsMagnitud = "R1"

	PeriodsMagnitudR2 PeriodsMagnitud = "R2"

	PeriodsMagnitudR3 PeriodsMagnitud = "R3"

	PeriodsMagnitudR4 PeriodsMagnitud = "R4"
)

// Defines values for PeriodsPeriod.
const (
	PeriodsPeriodP0 PeriodsPeriod = "P0"

	PeriodsPeriodP1 PeriodsPeriod = "P1"

	PeriodsPeriodP2 PeriodsPeriod = "P2"

	PeriodsPeriodP3 PeriodsPeriod = "P3"

	PeriodsPeriodP4 PeriodsPeriod = "P4"

	PeriodsPeriodP5 PeriodsPeriod = "P5"

	PeriodsPeriodP6 PeriodsPeriod = "P6"
)

// day_types object
type ExecuteServices struct {
	Cups          string              `json:"cups"`
	DistributorId string              `json:"distributor_id"`
	EndDate       openapi_types.Date  `json:"end_date"`
	StartDate     openapi_types.Date  `json:"start_date"`
	Type          ExecuteServicesType `json:"type"`
}

// ExecuteServicesType defines model for ExecuteServices.Type.
type ExecuteServicesType string

// MagnitudeFeatures defines model for MagnitudeFeatures.
type MagnitudeFeatures struct {
	Consum        *float32   `json:"consum,omitempty"`
	MaxDemand     *float32   `json:"max_demand,omitempty"`
	MaxDemandDate *time.Time `json:"max_demand_date,omitempty"`
	Reading       *float32   `json:"reading,omitempty"`
}

// MagnitudePeriodFeatures defines model for MagnitudePeriodFeatures.
type MagnitudePeriodFeatures struct {
	Ae *MagnitudeFeatures `json:"ae,omitempty"`
	Ai *MagnitudeFeatures `json:"ai,omitempty"`
	R1 *MagnitudeFeatures `json:"r1,omitempty"`
	R2 *MagnitudeFeatures `json:"r2,omitempty"`
	R3 *MagnitudeFeatures `json:"r3,omitempty"`
	R4 *MagnitudeFeatures `json:"r4,omitempty"`
}

// MonthlyClosure defines model for MonthlyClosure.
type MonthlyClosure struct {
	// Embedded fields due to inline allOf schema
	Id string `json:"id"`
	// Embedded struct due to allOf(#/components/schemas/MonthlyClosureBase)
	MonthlyClosureBase `yaml:",inline"`
}

// MonthlyClosureBase defines model for MonthlyClosureBase.
type MonthlyClosureBase struct {
	Periods           *[]Periods `json:"Periods,omitempty"`
	Cups              *string    `json:"cups,omitempty"`
	EndDate           string     `json:"end_date"`
	InitDate          string     `json:"init_date"`
	MeasureType       *string    `json:"measure_type,omitempty"`
	MeterSerialNumber *string    `json:"meter_serial_number,omitempty"`
	Origen            *string    `json:"origen,omitempty"`
	Status            string     `json:"status"`
}

// Periods defines model for Periods.
type Periods struct {
	Absolute    *float64        `json:"Absolute,omitempty"`
	Incremental *float64        `json:"Incremental,omitempty"`
	Magnitud    PeriodsMagnitud `json:"Magnitud"`
	Period      PeriodsPeriod   `json:"Period"`
}

// PeriodsMagnitud defines model for Periods.Magnitud.
type PeriodsMagnitud string

// PeriodsPeriod defines model for Periods.Period.
type PeriodsPeriod string

// ReadingClosure defines model for ReadingClosure.
type ReadingClosure struct {
	EndDate       *openapi_types.Date      `json:"end_date,omitempty"`
	MeasureDevice *string                  `json:"measure_device,omitempty"`
	MeasureType   *string                  `json:"measure_type,omitempty"`
	Origin        *string                  `json:"origin,omitempty"`
	P0            *MagnitudePeriodFeatures `json:"p0,omitempty"`
	P1            *MagnitudePeriodFeatures `json:"p1,omitempty"`
	P2            *MagnitudePeriodFeatures `json:"p2,omitempty"`
	P3            *MagnitudePeriodFeatures `json:"p3,omitempty"`
	P4            *MagnitudePeriodFeatures `json:"p4,omitempty"`
	P5            *MagnitudePeriodFeatures `json:"p5,omitempty"`
	P6            *MagnitudePeriodFeatures `json:"p6,omitempty"`
	StartDate     *openapi_types.Date      `json:"start_date,omitempty"`
}

// ProcessMeasuresResume defines model for processMeasuresResume.
type ProcessMeasuresResume struct {
	NextReadingClosure     *ReadingClosure `json:"next_reading_closure,omitempty"`
	PreviousReadingClosure *ReadingClosure `json:"previous_reading_closure,omitempty"`
}

// MonthlyClosureResponse defines model for MonthlyClosureResponse.
type MonthlyClosureResponse MonthlyClosure

// day_types object
type ExecuteProcessMeasure ExecuteServices

// MonthlyClosureRequest defines model for MonthlyClosureRequest.
type MonthlyClosureRequest MonthlyClosureBase

// GetBillingClosuresParams defines parameters for GetBillingClosures.
type GetBillingClosuresParams struct {
	// Id of the closures
	Id *string `json:"id,omitempty"`

	// Indicates if you want actual closures of id, the next or the before
	Moment *GetBillingClosuresParamsMoment `json:"moment,omitempty"`

	// Cups of service point
	Cups *string `json:"cups,omitempty"`

	// Start date of query by End date
	StartDate *openapi_types.Date `json:"start_date,omitempty"`

	// End date of query by End date
	EndDate *openapi_types.Date `json:"end_date,omitempty"`
}

// GetBillingClosuresParamsMoment defines parameters for GetBillingClosures.
type GetBillingClosuresParamsMoment string

// GetProcessMeasuresResumeByCupsParams defines parameters for GetProcessMeasuresResumeByCups.
type GetProcessMeasuresResumeByCupsParams struct {
	// process measure cups
	Cups string `json:"cups"`

	// distributor id
	DistributorId string `json:"distributor_id"`

	// start date of the monthly process measure
	StartDate openapi_types.Date `json:"start_date"`

	// end date of the monthly process measure
	EndDate openapi_types.Date `json:"end_date"`
}

// CreateBillingClosuresJSONRequestBody defines body for CreateBillingClosures for application/json ContentType.
type CreateBillingClosuresJSONRequestBody MonthlyClosureRequest

// UpdateBillingClosuresJSONRequestBody defines body for UpdateBillingClosures for application/json ContentType.
type UpdateBillingClosuresJSONRequestBody MonthlyClosureRequest

// ExecuteProcessMeasuresServicesJSONRequestBody defines body for ExecuteProcessMeasuresServices for application/json ContentType.
type ExecuteProcessMeasuresServicesJSONRequestBody ExecuteProcessMeasure
