apiVersion: apps/v1
kind: Deployment
metadata:
  name: measures-insert
  labels:
    app: measures-insert
spec:
  selector:
    matchLabels:
      app: measures-insert
  template:
    metadata:
      labels:
        app: measures-insert
    spec:
      containers:
        - name: measures-insert
          image: pubsub
          volumeMounts:
            - name: credentials
              mountPath: /usr/src/credentials
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /usr/src/credentials/sa.json
            - name: SUB_READ
              valueFrom:
                configMapKeyRef:
                  name: config-measures-pubsub
                  key: SUBSCRIPTION_INGESTION_MEASURES
            - name: PUBSUB_PROCESS
              value: GROSS_MEASURES
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
            - name: SERVICE
              value: measures_insert
            - name: MEASURE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-password
          envFrom:
            - configMapRef:
                name: config-postgres
            - configMapRef:
                name: config-measures-mongodb
            - configMapRef:
                name: config-measures-pubsub
            - configMapRef:
                name: config-measures
            - configMapRef:
                name: config-redis
            - configMapRef:
                name: config-process-measures
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: credentials
          secret:
            secretName: credentials
            items:
              - key: credentials_key
                path: sa.json