apiVersion: apps/v1
kind: Deployment
metadata:
  name: re-process-measures
  labels:
    app: re-process-measures
spec:
  selector:
    matchLabels:
      app: re-process-measures
  template:
    metadata:
      labels:
        app: re-process-measures
    spec:
      containers:
        - name: re-process-measures
          image: pubsub
          volumeMounts:
            - name: credentials
              mountPath: /usr/src/credentials
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /usr/src/credentials/sa.json
            - name: PUBSUB_PROCESS
              value: RE_PROCESS_MEASURES
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
            - name: SERVICE
              value: re_process_measures
            - name: MEASURE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-password
          envFrom:
            - configMapRef:
                name: config-postgres
            - configMapRef:
                name: config-measures-mongodb
            - configMapRef:
                name: config-measures-pubsub
            - configMapRef:
                name: config-measures
            - configMapRef:
                name: config-redis
            - configMapRef:
                name: config-process-measures
            - configMapRef:
                name: config-billing-measures
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: credentials
          secret:
            secretName: credentials
            items:
              - key: credentials_key
                path: sa.json
