apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-measures-insert-pubsub
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - external:
        metric:
          name: pubsub.googleapis.com|subscription|num_undelivered_messages
          selector:
            matchLabels:
              resource.labels.subscription_id: data-ingestion-measures-test-sub
        target:
          type: AverageValue
          averageValue: "10"
      type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: measures-insert
