apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-measures-parse-files-pubsub
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - external:
        metric:
          name: pubsub.googleapis.com|subscription|num_undelivered_messages
          selector:
            matchLabels:
              resource.labels.subscription_id: upload-files-sub
        target:
          type: AverageValue
          averageValue: "10"
      type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: measures-parse-files
